"""Conversation platform for Gemini Live."""

import logging
from homeassistant.components import conversation
from homeassistant.config_entries import ConfigEntry
from homeassistant.core import HomeAssistant
from homeassistant.helpers.entity_platform import AddEntitiesCallback
from homeassistant.helpers.intent import IntentResponse

_LOGGER = logging.getLogger(__name__)

async def async_setup_entry(
    hass: HomeAssistant,
    config_entry: ConfigEntry,
    async_add_entities: AddEntitiesCallback,
) -> None:
    """Set up Gemini Live Conversation platform."""
    async_add_entities([GeminiLiveConversationAgent(hass, config_entry)])


class GeminiLiveConversationAgent(conversation.ConversationEntity):
    """Gemini Live Pass-through Conversation Entity."""

    def __init__(self, hass: HomeAssistant, entry: ConfigEntry) -> None:
        """Initialize the agent."""
        self.hass = hass
        self.entry = entry
        self._name = "Gemini Live Pass-through"
        self._unique_id = f"{entry.entry_id}_conversation"

    @property
    def name(self) -> str:
        """Return the name of the entity."""
        return self._name

    @property
    def unique_id(self) -> str:
        """Return a unique ID."""
        return self._unique_id

    @property
    def supported_languages(self) -> list[str] | str:
        """Return supported languages."""
        return ["en", "en-US", "pl", "es", "fr", "de", "it"]

    async def async_process(
        self, user_input: conversation.ConversationInput
    ) -> conversation.ConversationResult:
        """Pass the response text from the STT stage straight through."""
        _LOGGER.debug("Conversation Agent received input text: %s", user_input.text)

        # The input text is already the response text generated by Gemini in the STT stage.
        # We wrap it inside an IntentResponse and return it immediately.
        intent_response = IntentResponse(language=user_input.language)
        intent_response.async_set_speech(user_input.text)

        return conversation.ConversationResult(
            response=intent_response,
            conversation_id=user_input.conversation_id,
        )
